Modification in select file - (id) auto increment

diff --git a/Insert_Table b/Insert_Table
--- a/Insert_Table
+++ b/Insert_Table
@@ -24,22 +24,20 @@ bg_cyan='\033[0;46m'
 
 Insert_Func ()
 {
-    echo -e "${red}\t\t\t  ---------------------------------------- ${clear}" 
-    echo -e "${red}\t\t\t  -----------Insert Into Table ----------- ${clear}"
-    echo -e "${red}\t\t\t  ----------------------------------------\n\n\n ${clear}" 
-
-    if [[  $1 == "" ]];
-    then 
+     
+    if [[  $1 == "" ]]; then 
 
         echo -e "${red}[ Error ] --- Can't Read Value You Entered --- ${clear}"
         Back_To_Menu
 
-    elif [[ `ls | grep -i "^$1.d$"` == "" && `ls | grep -i "^$1.m$"` == ""  ]]; then
+    elif [[ `ls | grep -i "^$1.d$"` == "" && `ls | grep -i "^$1.m$"` == ""  ]];then
         
-        echo -e "${red}[ Error ] --- Table Name Not Exist --- ${clear}" 
+        echo -e "${red}\n[ Error ] --- Table Name Not Exist --- ${clear}" 
         Back_To_Menu  
 
     else 
+        echo -e "${green}----------------------------------- * Insert Into Table * ------------------------------ \n${clear}"
+
         Insert_Values_Func $1
 
     fi
@@ -51,20 +49,14 @@ Insert_Func ()
 
 Back_To_Menu ()
 {
-    echo -e "${green} ---------------------------------------- ${clear}" 
-    echo -e "${green} ----------- * Select Menu * ------------ ${clear}"
-    echo -e "${green} ---------------------------------------- ${clear}" 
+        echo -e "${green}-------------------------------------- * Select Menu * ------------------------------------${clear}"
 
-        select Menu in  "Insert Table Name Again" "Back To (Main_Menu)" "Exit"
+        select Menu in  "Insert Table Name Again" "Exit"
         do
             case $Menu in
                 "Insert Table Name Again")
-                    Insert_Func
-                    break
-                    ;;
-                "BBack To (Main_Menu)")
-                    echo  "BBack To (Main_Menu)"
-                    ZeroXDBMS.sh
+                    read -p "Enter Table Name : " Table_Name
+                    Insert_Func $Table_Name 
                     break
                     ;;
                 "Exit")
@@ -85,49 +77,52 @@ Back_To_Menu ()
 
 Insert_Values_Func ()
 {
-echo -e "${green}---------------------------------------- Cloumn Name ------------------------------------${clear}"
+    declare val
+    declare line
+    echo -e "${green}------------------------------------- * Cloumn Name * ----------------------------------${clear}"
 
-for j in `awk -F " " '{print $1}' "$1.m"` 
-do 
-    arr_column+=("$j")
-done
-for j in `awk -F " " '{print $2}' "$1.m"` 
-do 
-    arr_Type+=("$j")
-done
+    for j in `awk -F " " '{print $1}' "$1.m"` 
+    do 
+        arr_column+=("$j")
+    done
+    for j in `awk -F " " '{print $2}' "$1.m"` 
+    do 
+        arr_Type+=("$j")
+    done
 
-column -t -s " " -o " --> " "$1.m"
-echo -e "${green}-----------------------------------------------------------------------------------------${clear}"
+    column -t -s " " -o " --> " "$1.m"
+    echo -e "${green}-----------------------------------------------------------------------------------------${clear}"
 
-for i in "${!arr_column[@]}" 
-do
-    read -p "Enter Value of ${arr_column[i]} " Value
+   
+    for i in "${!arr_column[@]}" 
+    do
+        if [[ $i = 0 ]];then
 
-    if [[ i == 0 ]];then
-        while ! [[ `cut -d ":" -f1 "$1" | grep "$value"` == "" ]];
-        do
-            read -p "[ Error ] --- Primary Key Should be uniqe --- " Value
-        done
-    fi
-    if [[ "${arr_Type[i]}" == "int" ]]; then
-        while ! [[ $Value =~ ^[0-9]*$  ]];
-        do
-            read -p "[ Error ] --- Enter Valid Input --- " Value
-        done
-    elif [[ "${arr_Type[i]}" == "var" ]];then
-        while ! [[ $Value =~ ^[a-zA-Z]*$ ]];
-        do
-            read -p "[ Error ] --- Enter Valid Input --- " Value
-        done
-    fi
+            val=$(($(wc -l $1.b | cut -d " " -f1 ) +1 ))
+            line=$line$val":"
 
-    if [[ $i == "${#arr_column[@]}" ]];then
-        line=$line$Value"\n"
-    else
-        line=$line$Value":"
-    fi
-done
-echo -e $line"\n" >> "$1.b"
+        else
+            read -p "$i- Enter Value of ${arr_column[i]} : " Value
+            if [[ "${arr_Type[i]}" == "int" ]]; then
+                while ! [[ $Value =~ ^[0-9]*$  ]];
+                do
+                    read -p "[ Error ] --- Enter Valid Input --- " Value
+                done
+            elif [[ "${arr_Type[i]}" == "var" ]];then
+                while ! [[ $Value =~ ^[a-zA-Z]*$ ]];
+                do
+                    read -p "[ Error ] --- Enter Valid Input --- " Value
+                done
+            fi
+
+            if ! [[ $i == "${!arr_column[@]}" ]];then
+                line=$line$Value":"
+                else
+                line=$line$Value
+            fi
+        fi  
+    done
+echo -e $line >> "$1.b"
 }
 
 
